image: node:16-bullseye

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - "build/"
    untracked: false
    when: on_success
    expire_in: 30 days

test:
  stage: test
  script:
    - npm test -- --watchAll=false